# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-twitter-plugin

# Site settings
title: "Jakub Homoly"
description: > # this means to ignore newlines until "email:"
   Software developer, Co-Founder of LimeDeck. You'll find a mish-mash of frontend, backend and API related articles here.

email: jakubhomoly@gmail.com
#blog logo
logo: "/assets/images/jh_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/sam-ferrara-270946.jpg"

name: 'Jakub Homoly'
author: 'Jakub Homoly'
author_image: "/assets/images/author.jpg"
author_bio: "Software developer. Writing about frontend, backend and API related things."

paginate:	5

url: "https://blog.homoly.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@insane141'

#fill in disqus shortname to use disqus
disqus: blog-homoly-me

google_analytics: UA-103843354-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/insane141
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/insanesvk
    desc:	Follow me on github
    share_url:
    share_title:
    share_link:
#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
